service: major-sins-infra
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
	
plugins:
  - serverless-finch

custom:
  client:
    bucketName: islamic-major-sins-bucket
    distributionFolder: client/build
    errorDocument: index.html